# Generated by Django 5.1.1 on 2024-09-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_cat',
            field=models.ImageField(upload_to='categoria'),
        ),
    ]
