# Generated by Django 5.1.1 on 2024-09-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_categoria_imagen_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='imagen_cat',
        ),
    ]
