# Generated by Django 5.1.1 on 2024-09-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_nosotros', models.CharField(max_length=70, verbose_name='Titulo Nosotros')),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='Nosotros')),
                ('gerente', models.CharField(max_length=70, verbose_name='Nombres Gerente')),
                ('disponible', models.BooleanField(default=True)),
                ('link_video', models.URLField(verbose_name='video')),
                ('titulo_experiencia', models.CharField(max_length=70, verbose_name='Titulo Experiencia')),
                ('contenido', models.TextField()),
                ('cantidad_proyectos', models.IntegerField(verbose_name='Cantidad de proyectos')),
                ('imagen_experiencia', models.ImageField(upload_to='experiencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nosotro',
                'verbose_name_plural': 'Nosotros',
            },
        ),
    ]
