# Generated by Django 5.1.1 on 2024-09-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_nosotros_imagen_gerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='link_video',
            field=models.CharField(max_length=200, verbose_name='video'),
        ),
    ]
