# Generated by Django 5.1.1 on 2024-09-17 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_nosotros_link_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre Habilida')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre Habilida')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=70, verbose_name='Nombres de Miembro de Equipo')),
                ('cargo', models.CharField(max_length=40, verbose_name='Foto')),
                ('foto', models.ImageField(upload_to='Miembros')),
                ('descripcion', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('link_facebook', models.CharField(max_length=200, verbose_name='Facebook')),
                ('link_youtube', models.CharField(max_length=200, verbose_name='Youtube')),
                ('link_twitter', models.CharField(max_length=200, verbose_name='Twitter')),
                ('link_linkedln', models.CharField(max_length=200, verbose_name='Linkedln')),
                ('link_telefono', models.IntegerField(verbose_name='Telefono')),
                ('link_correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('trabajo', models.TextField(verbose_name='Mi funcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.habilidad')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.logro')),
            ],
            options={
                'verbose_name': 'Mienbro',
                'verbose_name_plural': 'Miembros',
            },
        ),
    ]
