# Generated by Django 5.1.1 on 2024-09-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_cargo_alter_miembros_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembros',
            name='habilidad',
        ),
        migrations.RemoveField(
            model_name='miembros',
            name='logro',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='Logro',
        ),
    ]
