# Generated by Django 5.1.1 on 2024-09-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_miembros_habilidad_remove_miembros_logro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='foto',
            field=models.ImageField(blank=True, upload_to='Miembros'),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='link_correo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='link_linkedln',
            field=models.CharField(blank=True, max_length=200, verbose_name='Linkedln'),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='link_telefono',
            field=models.IntegerField(blank=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='link_twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='link_youtube',
            field=models.CharField(blank=True, max_length=200, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='imagen_gerente',
            field=models.ImageField(blank=True, upload_to='Nosotros/Gerente'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='link_video',
            field=models.CharField(blank=True, max_length=200, verbose_name='video'),
        ),
    ]
