# Generated by Django 5.1.1 on 2024-09-18 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_miembros_foto_alter_miembros_link_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_empleo', models.CharField(max_length=60, verbose_name='Titulo de Empleo')),
                ('foto', models.ImageField(blank=True, upload_to='Empleo')),
                ('descripcion', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('contenido', models.TextField(verbose_name='Contenido de Empleio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cargo')),
            ],
            options={
                'verbose_name': 'Empleo',
                'verbose_name_plural': 'Empleos',
            },
        ),
    ]
