# Generated by Django 5.1.1 on 2024-09-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_empleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='telefono',
            field=models.IntegerField(blank=True, default=2, verbose_name='Telefono Empresa'),
            preserve_default=False,
        ),
    ]
