# Generated by Django 5.1.1 on 2024-09-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_empleo_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_venta', models.CharField(max_length=60, verbose_name='Nombre x Vender')),
                ('foto', models.ImageField(blank=True, upload_to='Empleo')),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(blank=True, max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=30, verbose_name='Modelo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True)),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido de Empleio')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
