# Generated by Django 5.1.1 on 2024-09-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='foto',
            field=models.ImageField(blank=True, upload_to='Venta'),
        ),
    ]
