# Generated by Django 5.1.1 on 2024-09-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_historia', models.CharField(max_length=60, verbose_name='Titulo Historia')),
                ('descripcion', models.TextField(verbose_name='Descripcion de Acontecimiento')),
                ('foto', models.ImageField(blank=True, upload_to='Historia')),
                ('fecha_acontecimiento', models.DateTimeField(verbose_name='Año de Historia')),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
            },
        ),
    ]
