# Generated by Django 5.1.1 on 2024-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='fecha_acontecimiento',
            field=models.IntegerField(verbose_name='año de Historia'),
        ),
    ]
