# Generated by Django 5.1.1 on 2024-09-18 23:31

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_slug'),
        ('pages', '0014_alter_historia_fecha_acontecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='fecha_acontecimiento',
            field=models.IntegerField(verbose_name='Año de Historia'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_blog', models.CharField(max_length=50, verbose_name='Titulo Blog')),
                ('resumen', models.TextField()),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('imagenes', models.ImageField(upload_to='Blog/Fotos')),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
