# Generated by Django 5.1.1 on 2024-09-18 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_slug'),
        ('pages', '0015_alter_historia_fecha_acontecimiento_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_portafolio', models.CharField(max_length=70, verbose_name='Titulo Portafolio')),
                ('resumen', models.TextField()),
                ('imagenes', models.ImageField(upload_to='Portafolio')),
                ('disponible', models.BooleanField(default=True)),
                ('hicimos', models.TextField()),
                ('resultados', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
            },
        ),
        migrations.CreateModel(
            name='GaleriaPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=255, upload_to='Portafolio/imagenes')),
                ('portafolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.portafolio')),
            ],
            options={
                'verbose_name': 'Galeria Portafolio',
                'verbose_name_plural': 'Galeria Portafolios',
            },
        ),
    ]
