# Generated by Django 5.1.1 on 2024-09-19 15:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_portafolio_galeriaportafolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembros',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
