# Generated by Django 5.1.1 on 2024-09-19 16:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_miembros_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido'),
        ),
    ]
