# Generated by Django 5.1.1 on 2024-09-16 23:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descripcion',
            new_name='resumen',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='texto_blog',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='titulo',
        ),
        migrations.AddField(
            model_name='blog',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
