# Generated by Django 5.1.1 on 2024-09-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_descripcion_blog_resumen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
