# Generated by Django 5.1.1 on 2024-09-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombres Empresa')),
                ('logo', models.ImageField(blank=True, upload_to='Empresa')),
                ('descripcion', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Direccion Empresa')),
                ('direccion2', models.CharField(blank=True, max_length=200, verbose_name='Direccion Empresa')),
                ('link_facebook', models.CharField(blank=True, max_length=200, verbose_name='Facebook Empresa')),
                ('link_youtube', models.CharField(blank=True, max_length=200, verbose_name='Youtube Empresa')),
                ('link_twitter', models.CharField(blank=True, max_length=200, verbose_name='Twitter Empresa')),
                ('link_linkedln', models.CharField(blank=True, max_length=200, verbose_name='Linkedln Empresa')),
                ('telefono', models.IntegerField(blank=True, verbose_name='Telefono Empresa')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='Correo Empresa')),
                ('trabajo', models.TextField(verbose_name='Mi funcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_slider', models.CharField(max_length=70, verbose_name='Titulo Slider')),
                ('logo', models.ImageField(blank=True, upload_to='Empresa/Slider')),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
