# Generated by Django 5.1.1 on 2024-09-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='trabajo',
        ),
    ]
