# Generated by Django 5.1.1 on 2024-09-19 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_empresa_trabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='logo',
            new_name='imagen',
        ),
    ]
