# Generated by Django 5.1.1 on 2024-09-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_logo_slider_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_footer',
            field=models.ImageField(blank=True, upload_to='Empresa'),
        ),
    ]
