# Generated by Django 5.1.1 on 2024-09-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_empresa_logo_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen_cabecera_paginas',
            field=models.ImageField(blank=True, upload_to='Empresa'),
        ),
    ]
